// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAntGFtc37TIK0xDGK3l8KtqUFvrqqRNLw',
    appId: '1:728819774121:web:8a4ce11ec3f4534199efb8',
    messagingSenderId: '728819774121',
    projectId: 'fit-mind-5697f',
    authDomain: 'fit-mind-5697f.firebaseapp.com',
    storageBucket: 'fit-mind-5697f.firebasestorage.app',
    measurementId: 'G-G8PJY67WX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8r46FAHJO5PdjDFQtWPJovrP-VW730Hg',
    appId: '1:728819774121:android:545dcbf316606a4399efb8',
    messagingSenderId: '728819774121',
    projectId: 'fit-mind-5697f',
    storageBucket: 'fit-mind-5697f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh5bv_Du63Tva1bJdI0g5E6aon7qn9ymk',
    appId: '1:728819774121:ios:d40bd4e737bf4c8999efb8',
    messagingSenderId: '728819774121',
    projectId: 'fit-mind-5697f',
    storageBucket: 'fit-mind-5697f.firebasestorage.app',
    iosBundleId: 'com.example.fitmindAiFitnessMentalHealthCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh5bv_Du63Tva1bJdI0g5E6aon7qn9ymk',
    appId: '1:728819774121:ios:d40bd4e737bf4c8999efb8',
    messagingSenderId: '728819774121',
    projectId: 'fit-mind-5697f',
    storageBucket: 'fit-mind-5697f.firebasestorage.app',
    iosBundleId: 'com.example.fitmindAiFitnessMentalHealthCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAntGFtc37TIK0xDGK3l8KtqUFvrqqRNLw',
    appId: '1:728819774121:web:ccf5ed6ee32fe8c699efb8',
    messagingSenderId: '728819774121',
    projectId: 'fit-mind-5697f',
    authDomain: 'fit-mind-5697f.firebaseapp.com',
    storageBucket: 'fit-mind-5697f.firebasestorage.app',
    measurementId: 'G-0550YLYBRD',
  );
}
