// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEcsx9tjUz7q2xlcTUY7VdHbQ2HIrJRyY',
    appId: '1:930780173261:web:b7ff9319d9ca2039a8ea84',
    messagingSenderId: '930780173261',
    projectId: 'fitness-1f42d',
    authDomain: 'fitness-1f42d.firebaseapp.com',
    storageBucket: 'fitness-1f42d.firebasestorage.app',
    measurementId: 'G-8S96J8RGF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvMaxzZ92abU0k7Q-5JVx58vMLbCU1VI8',
    appId: '1:930780173261:android:159225c9d42b82ada8ea84',
    messagingSenderId: '930780173261',
    projectId: 'fitness-1f42d',
    storageBucket: 'fitness-1f42d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeQdcEzjSmfuJMFVn-jSUFnN0E_0XVZqA',
    appId: '1:930780173261:ios:5c4ba5b95475eb67a8ea84',
    messagingSenderId: '930780173261',
    projectId: 'fitness-1f42d',
    storageBucket: 'fitness-1f42d.firebasestorage.app',
    iosBundleId: 'com.example.fitmindAiFitnessMentalHealthCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeQdcEzjSmfuJMFVn-jSUFnN0E_0XVZqA',
    appId: '1:930780173261:ios:5c4ba5b95475eb67a8ea84',
    messagingSenderId: '930780173261',
    projectId: 'fitness-1f42d',
    storageBucket: 'fitness-1f42d.firebasestorage.app',
    iosBundleId: 'com.example.fitmindAiFitnessMentalHealthCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEcsx9tjUz7q2xlcTUY7VdHbQ2HIrJRyY',
    appId: '1:930780173261:web:c5d90e204d93f618a8ea84',
    messagingSenderId: '930780173261',
    projectId: 'fitness-1f42d',
    authDomain: 'fitness-1f42d.firebaseapp.com',
    storageBucket: 'fitness-1f42d.firebasestorage.app',
    measurementId: 'G-3Z7Z7FDLFR',
  );

}